# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/xup/fpga_flow/TFMV2/pblaze_s/pblaze_s.cache/wt [current_project]
set_property parent.project_path C:/xup/fpga_flow/TFMV2/pblaze_s/pblaze_s.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part digilentinc.com:zybo:part0:1.0 [current_project]
set_property ip_repo_paths {
  c:/xup/fpga_flow/TFMV2/pblaze_s/pblaze_s.srcs/sources_1
  c:/xup/fpga_flow/TFMV2/ip_repo/pblaze_s_1.0
  c:/xup/fpga_flow/TFMV2/ip_repo/pblase_s_1.0
  c:/xup/fpga_flow/TFMV2/ip_repo/myip_1.0
  c:/xup/fpga_flow/TFM/ip_repo/pBlaze_1.0
  c:/xup/fpga_flow/TFMV2/ip_repo
} [current_project]
set_property ip_output_repo c:/xup/fpga_flow/TFMV2/pblaze_s/pblaze_s.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files -quiet C:/xup/fpga_flow/TFMV2/pblaze_s/pblaze_s.runs/mult_gen_0_synth_1/mult_gen_0.dcp
set_property used_in_implementation false [get_files C:/xup/fpga_flow/TFMV2/pblaze_s/pblaze_s.runs/mult_gen_0_synth_1/mult_gen_0.dcp]
read_vhdl -library xil_defaultlib {
  C:/xup/fpga_flow/TFMV2/pblaze_s/pblaze_s.srcs/sources_1/imports/hdl/CONSTANTES.vhd
  C:/xup/fpga_flow/TFMV2/pblaze_s/pblaze_s.srcs/sources_1/imports/hdl/Cordic.vhd
  C:/xup/fpga_flow/TFMV2/pblaze_s/pblaze_s.srcs/sources_1/imports/src/kcpsm6.vhd
  C:/xup/fpga_flow/TFMV2/pblaze_s/pblaze_s.srcs/sources_1/imports/src/Proccessor.vhd
}
read_ip -quiet C:/xup/fpga_flow/TFMV2/pblaze_s/pblaze_s.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci
set_property is_locked true [get_files C:/xup/fpga_flow/TFMV2/pblaze_s/pblaze_s.srcs/sources_1/ip/mult_gen_0/mult_gen_0.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}

synth_design -top Processor -part xc7z010clg400-1


write_checkpoint -force -noxdef Processor.dcp

catch { report_utilization -file Processor_utilization_synth.rpt -pb Processor_utilization_synth.pb }
