# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab2emb_v1/lab2emb_v1.srcs/sources_1/bd/systemv1/ip/systemv1_processing_system7_0_0/systemv1_processing_system7_0_0.xci
# IP: The module: 'systemv1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab2emb_v1/lab2emb_v1.srcs/sources_1/bd/systemv1/ip/systemv1_processing_system7_0_0/systemv1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'systemv1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab2emb_v1/lab2emb_v1.srcs/sources_1/bd/systemv1/ip/systemv1_processing_system7_0_0/systemv1_processing_system7_0_0.xci
# IP: The module: 'systemv1_processing_system7_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab2emb_v1/lab2emb_v1.srcs/sources_1/bd/systemv1/ip/systemv1_processing_system7_0_0/systemv1_processing_system7_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'systemv1_processing_system7_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
