# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/system_axi_smc_0.xci
# IP: The module: 'system_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/bd_44e3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_31/bd_44e3_s00a2s_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_37/bd_44e3_m00s2a_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_38/bd_44e3_m00e_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_32/bd_44e3_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_33/bd_44e3_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_34/bd_44e3_sawn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_35/bd_44e3_swn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_36/bd_44e3_sbn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_28/bd_44e3_s00mmu_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_29/bd_44e3_s00tr_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_30/bd_44e3_s00sic_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_26/bd_44e3_one_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_27/bd_44e3_psr_aclk_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_31/bd_44e3_s00a2s_2_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_37/bd_44e3_m00s2a_2_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_32/bd_44e3_sarn_2_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_33/bd_44e3_srn_2_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_34/bd_44e3_sawn_2_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_35/bd_44e3_swn_2_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_36/bd_44e3_sbn_2_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_27/bd_44e3_psr_aclk_2_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_27/bd_44e3_psr_aclk_2.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/system_axi_smc_0.xci
# IP: The module: 'system_axi_smc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/bd_44e3.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_31/bd_44e3_s00a2s_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_37/bd_44e3_m00s2a_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_38/bd_44e3_m00e_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_32/bd_44e3_sarn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_33/bd_44e3_srn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_34/bd_44e3_sawn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_35/bd_44e3_swn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_36/bd_44e3_sbn_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_28/bd_44e3_s00mmu_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_29/bd_44e3_s00tr_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_30/bd_44e3_s00sic_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_26/bd_44e3_one_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_27/bd_44e3_psr_aclk_2.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_31/bd_44e3_s00a2s_2_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_37/bd_44e3_m00s2a_2_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_32/bd_44e3_sarn_2_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_33/bd_44e3_srn_2_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_34/bd_44e3_sawn_2_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_35/bd_44e3_swn_2_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_36/bd_44e3_sbn_2_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_27/bd_44e3_psr_aclk_2_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/bd_0/ip/ip_27/bd_44e3_psr_aclk_2.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_smc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
