# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab6/lab6.srcs/sources_1/ip/ila_led/ila_led.xci
# IP: The module: 'ila_led' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab6/lab6.srcs/sources_1/ip/ila_led/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_led'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab6/lab6.srcs/sources_1/ip/ila_led/ila_led_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_led'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab6/lab6.srcs/sources_1/ip/ila_led/ila_led.xci
# IP: The module: 'ila_led' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab6/lab6.srcs/sources_1/ip/ila_led/ila_v6_2/constraints/ila.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_led'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab6/lab6.srcs/sources_1/ip/ila_led/ila_led_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'ila_led'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
