# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/system_axi_smc_1_0.xci
# IP: The module: 'system_axi_smc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/bd_2721.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_40/bd_2721_s00a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_46/bd_2721_m00s2a_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_53/bd_2721_m01s2a_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_59/bd_2721_m01e_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_54/bd_2721_m01arn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_55/bd_2721_m01rn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_56/bd_2721_m01awn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_57/bd_2721_m01wn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_58/bd_2721_m01bn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_52/bd_2721_m00e_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_47/bd_2721_m00arn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_48/bd_2721_m00rn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_49/bd_2721_m00awn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_50/bd_2721_m00wn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_51/bd_2721_m00bn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_41/bd_2721_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_42/bd_2721_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_43/bd_2721_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_44/bd_2721_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_45/bd_2721_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_37/bd_2721_s00mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_38/bd_2721_s00tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_39/bd_2721_s00sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_32/bd_2721_arsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_33/bd_2721_rsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_34/bd_2721_awsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_35/bd_2721_wsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_36/bd_2721_bsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_30/bd_2721_one_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_31/bd_2721_psr_aclk_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_40/bd_2721_s00a2s_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_46/bd_2721_m00s2a_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_53/bd_2721_m01s2a_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_54/bd_2721_m01arn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_55/bd_2721_m01rn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_56/bd_2721_m01awn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_57/bd_2721_m01wn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_58/bd_2721_m01bn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_47/bd_2721_m00arn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_48/bd_2721_m00rn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_49/bd_2721_m00awn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_50/bd_2721_m00wn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_51/bd_2721_m00bn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_41/bd_2721_sarn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_42/bd_2721_srn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_43/bd_2721_sawn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_44/bd_2721_swn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_45/bd_2721_sbn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_32/bd_2721_arsw_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_33/bd_2721_rsw_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_34/bd_2721_awsw_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_35/bd_2721_wsw_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_36/bd_2721_bsw_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_31/bd_2721_psr_aclk_1_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_31/bd_2721_psr_aclk_1.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_smc_1_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/system_axi_smc_1_0.xci
# IP: The module: 'system_axi_smc_1_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# Block Designs: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/bd_2721.bd
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_40/bd_2721_s00a2s_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_46/bd_2721_m00s2a_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_53/bd_2721_m01s2a_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_59/bd_2721_m01e_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_54/bd_2721_m01arn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_55/bd_2721_m01rn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_56/bd_2721_m01awn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_57/bd_2721_m01wn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_58/bd_2721_m01bn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_52/bd_2721_m00e_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_47/bd_2721_m00arn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_48/bd_2721_m00rn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_49/bd_2721_m00awn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_50/bd_2721_m00wn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_51/bd_2721_m00bn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_41/bd_2721_sarn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_42/bd_2721_srn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_43/bd_2721_sawn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_44/bd_2721_swn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_45/bd_2721_sbn_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_37/bd_2721_s00mmu_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_38/bd_2721_s00tr_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_39/bd_2721_s00sic_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_32/bd_2721_arsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_33/bd_2721_rsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_34/bd_2721_awsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_35/bd_2721_wsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_36/bd_2721_bsw_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_30/bd_2721_one_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_31/bd_2721_psr_aclk_1.xci
# DONT_TOUCH constraint suppressed by (parent) sub-design file.

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_40/bd_2721_s00a2s_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_46/bd_2721_m00s2a_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_53/bd_2721_m01s2a_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_54/bd_2721_m01arn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_55/bd_2721_m01rn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_56/bd_2721_m01awn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_57/bd_2721_m01wn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_58/bd_2721_m01bn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_47/bd_2721_m00arn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_48/bd_2721_m00rn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_49/bd_2721_m00awn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_50/bd_2721_m00wn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_51/bd_2721_m00bn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_41/bd_2721_sarn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_42/bd_2721_srn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_43/bd_2721_sawn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_44/bd_2721_swn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_45/bd_2721_sbn_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_32/bd_2721_arsw_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_33/bd_2721_rsw_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_34/bd_2721_awsw_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_35/bd_2721_wsw_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_36/bd_2721_bsw_1_ooc.xdc

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_31/bd_2721_psr_aclk_1_board.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/bd_0/ip/ip_31/bd_2721_psr_aclk_1.xdc
# DONT_TOUCH constraint suppressed by parent sub-design file.

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/lab4aes/lab4aes.srcs/sources_1/bd/system/ip/system_axi_smc_1_0/ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_smc_1_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
