set_property SRC_FILE_INFO {cfile:C:/xup/fpga_flow/TFMV2/TFM_GE/TFM_GE.srcs/constrs_1/imports/Desktop/zybo.xdc rfile:../../../TFM_GE.srcs/constrs_1/imports/Desktop/zybo.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports {btn_tri_io[0]}]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[2]}]
set_property src_info {type:XDC file:1 line:8 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[6]}]
set_property src_info {type:XDC file:1 line:9 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[3]}]
set_property src_info {type:XDC file:1 line:10 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[5]}]
set_property src_info {type:XDC file:1 line:11 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[7]}]
set_property src_info {type:XDC file:1 line:12 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[1]}]
set_property src_info {type:XDC file:1 line:13 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[0]}]
set_property src_info {type:XDC file:1 line:14 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[4]}]
set_property src_info {type:XDC file:1 line:15 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[3]}]
set_property src_info {type:XDC file:1 line:16 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[7]}]
set_property src_info {type:XDC file:1 line:17 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[5]}]
set_property src_info {type:XDC file:1 line:18 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[1]}]
set_property src_info {type:XDC file:1 line:19 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[2]}]
set_property src_info {type:XDC file:1 line:20 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[6]}]
set_property src_info {type:XDC file:1 line:21 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[4]}]
set_property src_info {type:XDC file:1 line:22 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[0]}]
set_property src_info {type:XDC file:1 line:23 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/reset0]
set_property src_info {type:XDC file:1 line:24 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/reset_reg_n_0]
set_property src_info {type:XDC file:1 line:25 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[4]}]
set_property src_info {type:XDC file:1 line:26 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[0]}]
set_property src_info {type:XDC file:1 line:27 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[7]}]
set_property src_info {type:XDC file:1 line:28 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[3]}]
set_property src_info {type:XDC file:1 line:29 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[1]}]
set_property src_info {type:XDC file:1 line:30 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[2]}]
set_property src_info {type:XDC file:1 line:31 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[5]}]
set_property src_info {type:XDC file:1 line:32 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[6]}]
set_property src_info {type:XDC file:1 line:33 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/reset_reg]
set_property src_info {type:XDC file:1 line:36 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe71 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/reset_reg_n_0]]
set_property src_info {type:XDC file:1 line:40 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_5]
set_property src_info {type:XDC file:1 line:41 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_1]
set_property src_info {type:XDC file:1 line:42 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_0]
set_property src_info {type:XDC file:1 line:43 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_4]
set_property src_info {type:XDC file:1 line:44 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_3]
set_property src_info {type:XDC file:1 line:45 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_2]
set_property src_info {type:XDC file:1 line:46 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_6]
set_property src_info {type:XDC file:1 line:47 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_7]
set_property src_info {type:XDC file:1 line:49 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[0]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[1]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[2]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[3]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[4]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[5]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[6]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[7]}]]
set_property src_info {type:XDC file:1 line:50 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe43 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/reset_reg]]
set_property src_info {type:XDC file:1 line:54 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe42 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/reset0]]
set_property src_info {type:XDC file:1 line:56 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe42 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_0]]
set_property src_info {type:XDC file:1 line:57 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe43 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_1]]
set_property src_info {type:XDC file:1 line:58 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe44 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_2]]
set_property src_info {type:XDC file:1 line:59 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe45 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_3]]
set_property src_info {type:XDC file:1 line:60 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe46 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_4]]
set_property src_info {type:XDC file:1 line:61 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe47 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_5]]
set_property src_info {type:XDC file:1 line:62 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe48 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_6]]
set_property src_info {type:XDC file:1 line:63 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe49 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_7]]
set_property src_info {type:XDC file:1 line:66 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[0]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[1]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[2]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[3]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[4]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[5]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[6]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[7]}]]
set_property src_info {type:XDC file:1 line:67 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[0]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[1]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[2]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[3]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[4]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[5]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[6]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[7]}]]
set_property src_info {type:XDC file:1 line:68 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {system_i/pBlaze_0/s_axi_araddr[2]} {system_i/pBlaze_0/s_axi_araddr[3]}]]
set_property src_info {type:XDC file:1 line:69 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {system_i/pBlaze_0_address[2]} {system_i/pBlaze_0_address[3]} {system_i/pBlaze_0_address[4]} {system_i/pBlaze_0_address[5]} {system_i/pBlaze_0_address[6]} {system_i/pBlaze_0_address[7]} {system_i/pBlaze_0_address[8]} {system_i/pBlaze_0_address[9]} {system_i/pBlaze_0_address[10]} {system_i/pBlaze_0_address[11]} {system_i/pBlaze_0_address[12]} {system_i/pBlaze_0_address[13]}]]
set_property src_info {type:XDC file:1 line:70 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list system_i/pBlaze_0/pB_rdy]]
set_property src_info {type:XDC file:1 line:71 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list system_i/pBlaze_0_ram_enable]]
set_property src_info {type:XDC file:1 line:75 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe26 [get_nets [list system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1_n_8]]
set_property src_info {type:XDC file:1 line:76 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe28 [get_nets [list system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1_n_10]]
set_property src_info {type:XDC file:1 line:77 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe29 [get_nets [list system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1_n_11]]
set_property src_info {type:XDC file:1 line:79 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe26 [get_nets [list system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1_n_9]]
set_property src_info {type:XDC file:1 line:81 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1_n_8]
set_property src_info {type:XDC file:1 line:82 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe26 [get_nets [list system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1_n_8]]
set_property src_info {type:XDC file:1 line:84 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_12_in[0]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_12_in[1]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_12_in[2]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_12_in[3]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_12_in[4]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_12_in[5]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_12_in[6]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_12_in[7]}]]
set_property src_info {type:XDC file:1 line:87 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[14]}]
set_property src_info {type:XDC file:1 line:88 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[12]}]
set_property src_info {type:XDC file:1 line:89 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[24]}]
set_property src_info {type:XDC file:1 line:90 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[28]}]
set_property src_info {type:XDC file:1 line:91 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[4]}]
set_property src_info {type:XDC file:1 line:92 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[29]}]
set_property src_info {type:XDC file:1 line:93 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[8]}]
set_property src_info {type:XDC file:1 line:94 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[20]}]
set_property src_info {type:XDC file:1 line:95 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[1]}]
set_property src_info {type:XDC file:1 line:96 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[31]}]
set_property src_info {type:XDC file:1 line:97 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[30]}]
set_property src_info {type:XDC file:1 line:98 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[16]}]
set_property src_info {type:XDC file:1 line:99 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[23]}]
set_property src_info {type:XDC file:1 line:100 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[5]}]
set_property src_info {type:XDC file:1 line:101 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[17]}]
set_property src_info {type:XDC file:1 line:102 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[10]}]
set_property src_info {type:XDC file:1 line:103 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[6]}]
set_property src_info {type:XDC file:1 line:104 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[7]}]
set_property src_info {type:XDC file:1 line:105 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[9]}]
set_property src_info {type:XDC file:1 line:106 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[11]}]
set_property src_info {type:XDC file:1 line:107 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[13]}]
set_property src_info {type:XDC file:1 line:108 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[22]}]
set_property src_info {type:XDC file:1 line:109 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[27]}]
set_property src_info {type:XDC file:1 line:110 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[2]}]
set_property src_info {type:XDC file:1 line:111 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[21]}]
set_property src_info {type:XDC file:1 line:112 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[18]}]
set_property src_info {type:XDC file:1 line:113 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[19]}]
set_property src_info {type:XDC file:1 line:114 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[15]}]
set_property src_info {type:XDC file:1 line:115 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[26]}]
set_property src_info {type:XDC file:1 line:116 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[3]}]
set_property src_info {type:XDC file:1 line:117 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[25]}]
set_property src_info {type:XDC file:1 line:118 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/rdy_tmp2]
set_property src_info {type:XDC file:1 line:119 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe32 [get_nets [list system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/op_rdy]]
set_property src_info {type:XDC file:1 line:121 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[29]}]
set_property src_info {type:XDC file:1 line:122 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[31]}]
set_property src_info {type:XDC file:1 line:123 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[12]}]
set_property src_info {type:XDC file:1 line:124 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1_n_5]
set_property src_info {type:XDC file:1 line:125 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[19]}]
set_property src_info {type:XDC file:1 line:126 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[4]}]
set_property src_info {type:XDC file:1 line:127 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[4]}]
set_property src_info {type:XDC file:1 line:128 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[20]}]
set_property src_info {type:XDC file:1 line:129 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[26]}]
set_property src_info {type:XDC file:1 line:130 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_Areg_reg_n_0_[3]}]
set_property src_info {type:XDC file:1 line:131 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[12]}]
set_property src_info {type:XDC file:1 line:132 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1_n_6]
set_property src_info {type:XDC file:1 line:133 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[11]}]
set_property src_info {type:XDC file:1 line:134 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[18]}]
set_property src_info {type:XDC file:1 line:135 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[21]}]
set_property src_info {type:XDC file:1 line:136 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[2]}]
set_property src_info {type:XDC file:1 line:137 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[24]}]
set_property src_info {type:XDC file:1 line:138 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[7]}]
set_property src_info {type:XDC file:1 line:139 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[15]}]
set_property src_info {type:XDC file:1 line:140 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_Areg_reg_n_0_[0]}]
set_property src_info {type:XDC file:1 line:141 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[8]}]
set_property src_info {type:XDC file:1 line:142 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[16]}]
set_property src_info {type:XDC file:1 line:143 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1_n_11]
set_property src_info {type:XDC file:1 line:144 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1_n_9]
set_property src_info {type:XDC file:1 line:145 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[2]}]
set_property src_info {type:XDC file:1 line:146 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[10]}]
set_property src_info {type:XDC file:1 line:147 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_Areg_reg_n_0_[7]}]
set_property src_info {type:XDC file:1 line:148 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[6]}]
set_property src_info {type:XDC file:1 line:149 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[25]}]
set_property src_info {type:XDC file:1 line:150 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[23]}]
set_property src_info {type:XDC file:1 line:151 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_Areg_reg_n_0_[6]}]
set_property src_info {type:XDC file:1 line:152 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[0]}]
set_property src_info {type:XDC file:1 line:153 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_Areg_reg_n_0_[1]}]
set_property src_info {type:XDC file:1 line:154 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1_n_4]
set_property src_info {type:XDC file:1 line:155 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[22]}]
set_property src_info {type:XDC file:1 line:156 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[9]}]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_Areg_reg_n_0_[4]}]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[5]}]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[14]}]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[5]}]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[18]}]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[15]}]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[29]}]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[8]}]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[0]}]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[3]}]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[1]}]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[27]}]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[16]}]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[20]}]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[30]}]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1_n_10]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1_n_7]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_Areg_reg_n_0_[5]}]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_Areg_reg_n_0_[2]}]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[13]}]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[23]}]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[26]}]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[28]}]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[22]}]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[19]}]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/y_tmp[17]}]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[14]}]
set_property src_info {type:XDC file:1 line:184 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[3]}]
set_property src_info {type:XDC file:1 line:185 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[11]}]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[17]}]
set_property src_info {type:XDC file:1 line:187 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[27]}]
set_property src_info {type:XDC file:1 line:188 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[21]}]
set_property src_info {type:XDC file:1 line:189 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[25]}]
set_property src_info {type:XDC file:1 line:190 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[9]}]
set_property src_info {type:XDC file:1 line:191 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[28]}]
set_property src_info {type:XDC file:1 line:192 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[24]}]
set_property src_info {type:XDC file:1 line:193 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[6]}]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[7]}]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[10]}]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[1]}]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[30]}]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/z_ip_reg_n_0_[13]}]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[1]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[2]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[3]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[5]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[6]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[7]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[9]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[10]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[11]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[13]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[14]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[18]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[19]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[21]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[22]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[23]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[25]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[26]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[27]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[29]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[30]}]]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/rdy_tmp2]]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[1]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[2]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[3]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[4]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[5]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[6]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[7]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[8]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[9]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[10]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[11]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[12]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[13]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[14]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[15]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[16]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[17]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[18]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[19]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[20]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[21]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[22]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[23]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[24]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[25]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[26]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[27]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[28]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[29]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[30]} {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/x_tmp[31]}]]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/rdy_tmp2]]
set_property src_info {type:XDC file:1 line:212 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/pBlaze_0_ram_enable]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_12_in[6]}]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[13]}]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_10_in[2]}]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_10_in[7]}]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/op_en]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/op_en]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/s_axi_araddr[2]}]
set_property src_info {type:XDC file:1 line:221 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_11_in[4]}]
set_property src_info {type:XDC file:1 line:222 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_11_in[1]}]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_12_in[5]}]
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_10_in[6]}]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_10_in[0]}]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/port_id[4]}]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/port_id[7]}]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/port_id[3]}]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/cordic_v1/op_rdy]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/port_id[1]}]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_12_in[4]}]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[15]}]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/op_rdy]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/port_id[5]}]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/port_id[2]}]
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_Areg[7]}]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_11_in[5]}]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_11_in[7]}]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_10_in[4]}]
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_12_in[1]}]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_10_in[1]}]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/port_id[6]}]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_11_in[3]}]
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_10_in[3]}]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/pBlaze_0/pB_rdy]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_Areg[31]}]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[14]}]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/s_axi_araddr[3]}]
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_12_in[0]}]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_11_in[2]}]
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_12_in[7]}]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_12_in[2]}]
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_10_in[5]}]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_11_in[0]}]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_11_in[6]}]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/p_12_in[3]}]
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_Areg[23]}]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_Areg[15]}]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/ps7_0_axi_periph_n_27]
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/ps7_0_axi_periph_n_26]
set_property src_info {type:XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/ps7_0_axi_periph_n_59]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/ps7_0_axi_periph_n_60]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/ps7_0_axi_periph_n_61]
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/ps7_0_axi_periph_n_62]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/ps7_0_axi_periph_n_63]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe33 [get_nets [list system_i/ps7_0_axi_periph_n_26]]
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe34 [get_nets [list system_i/ps7_0_axi_periph_n_27]]
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe58 [get_nets [list system_i/ps7_0_axi_periph_n_59]]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe59 [get_nets [list system_i/ps7_0_axi_periph_n_60]]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe60 [get_nets [list system_i/ps7_0_axi_periph_n_61]]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe61 [get_nets [list system_i/ps7_0_axi_periph_n_62]]
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe62 [get_nets [list system_i/ps7_0_axi_periph_n_63]]
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0_address[1]}]
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0_address[0]}]
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0_address[14]}]
set_property src_info {type:XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0_address[15]}]
set_property src_info {type:XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[9]}]
set_property src_info {type:XDC file:1 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[11]}]
set_property src_info {type:XDC file:1 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[4]}]
set_property src_info {type:XDC file:1 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[2]}]
set_property src_info {type:XDC file:1 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[5]}]
set_property src_info {type:XDC file:1 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[3]}]
set_property src_info {type:XDC file:1 line:353 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[16]}]
set_property src_info {type:XDC file:1 line:354 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[1]}]
set_property src_info {type:XDC file:1 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[14]}]
set_property src_info {type:XDC file:1 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[15]}]
set_property src_info {type:XDC file:1 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[7]}]
set_property src_info {type:XDC file:1 line:365 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[0]}]
set_property src_info {type:XDC file:1 line:366 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[13]}]
set_property src_info {type:XDC file:1 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[12]}]
set_property src_info {type:XDC file:1 line:368 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[8]}]
set_property src_info {type:XDC file:1 line:369 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[10]}]
set_property src_info {type:XDC file:1 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[6]}]
set_property src_info {type:XDC file:1 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[17]}]
set_property src_info {type:XDC file:1 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_1]
set_property src_info {type:XDC file:1 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_24]
set_property src_info {type:XDC file:1 line:384 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_13]
set_property src_info {type:XDC file:1 line:385 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0_address[2]}]
set_property src_info {type:XDC file:1 line:386 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_12]
set_property src_info {type:XDC file:1 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_11]
set_property src_info {type:XDC file:1 line:388 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/pBlaze_0_pB_rdy]
set_property src_info {type:XDC file:1 line:389 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_45]
set_property src_info {type:XDC file:1 line:390 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_36]
set_property src_info {type:XDC file:1 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_23]
set_property src_info {type:XDC file:1 line:392 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_52]
set_property src_info {type:XDC file:1 line:393 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_44]
set_property src_info {type:XDC file:1 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_20]
set_property src_info {type:XDC file:1 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_35]
set_property src_info {type:XDC file:1 line:396 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_25]
set_property src_info {type:XDC file:1 line:397 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_6]
set_property src_info {type:XDC file:1 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_10]
set_property src_info {type:XDC file:1 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_5]
set_property src_info {type:XDC file:1 line:400 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_37]
set_property src_info {type:XDC file:1 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_48]
set_property src_info {type:XDC file:1 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_0]
set_property src_info {type:XDC file:1 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_14]
set_property src_info {type:XDC file:1 line:404 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_15]
set_property src_info {type:XDC file:1 line:405 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_16]
set_property src_info {type:XDC file:1 line:406 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0_address[11]}]
set_property src_info {type:XDC file:1 line:407 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_17]
set_property src_info {type:XDC file:1 line:408 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_18]
set_property src_info {type:XDC file:1 line:409 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_19]
set_property src_info {type:XDC file:1 line:410 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_2]
set_property src_info {type:XDC file:1 line:411 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_21]
set_property src_info {type:XDC file:1 line:412 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_22]
set_property src_info {type:XDC file:1 line:413 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_3]
set_property src_info {type:XDC file:1 line:414 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_33]
set_property src_info {type:XDC file:1 line:415 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_34]
set_property src_info {type:XDC file:1 line:416 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_38]
set_property src_info {type:XDC file:1 line:417 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_39]
set_property src_info {type:XDC file:1 line:418 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_4]
set_property src_info {type:XDC file:1 line:419 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_40]
set_property src_info {type:XDC file:1 line:420 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_41]
set_property src_info {type:XDC file:1 line:421 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_42]
set_property src_info {type:XDC file:1 line:422 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_43]
set_property src_info {type:XDC file:1 line:423 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_46]
set_property src_info {type:XDC file:1 line:424 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_47]
set_property src_info {type:XDC file:1 line:425 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_49]
set_property src_info {type:XDC file:1 line:426 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_50]
set_property src_info {type:XDC file:1 line:427 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_51]
set_property src_info {type:XDC file:1 line:428 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_53]
set_property src_info {type:XDC file:1 line:429 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_54]
set_property src_info {type:XDC file:1 line:430 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_55]
set_property src_info {type:XDC file:1 line:431 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_56]
set_property src_info {type:XDC file:1 line:432 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_57]
set_property src_info {type:XDC file:1 line:433 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_58]
set_property src_info {type:XDC file:1 line:434 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_7]
set_property src_info {type:XDC file:1 line:435 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_8]
set_property src_info {type:XDC file:1 line:436 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/ps7_0_axi_periph_n_9]
set_property src_info {type:XDC file:1 line:437 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0_address[13]}]
set_property src_info {type:XDC file:1 line:438 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0_address[8]}]
set_property src_info {type:XDC file:1 line:439 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0_address[9]}]
set_property src_info {type:XDC file:1 line:440 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0_address[6]}]
set_property src_info {type:XDC file:1 line:441 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0_address[3]}]
set_property src_info {type:XDC file:1 line:442 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/pBlaze_0/U0/ram_enable]
set_property src_info {type:XDC file:1 line:443 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0_address[5]}]
set_property src_info {type:XDC file:1 line:444 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0_address[10]}]
set_property src_info {type:XDC file:1 line:445 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0_address[7]}]
set_property src_info {type:XDC file:1 line:446 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0_address[4]}]
set_property src_info {type:XDC file:1 line:447 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0_address[12]}]
set_property src_info {type:XDC file:1 line:449 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M14 [get_ports {data_r_s_axi_rdataa[0]}]
set_property src_info {type:XDC file:1 line:451 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN M15 [get_ports {data_r_s_axi_rdatab[0]}]
set_property src_info {type:XDC file:1 line:452 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN G14 [get_ports {data_r_s_axi_rdatac[0]}]
set_property src_info {type:XDC file:1 line:453 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN D18 [get_ports {data_r_s_axi_rdatad[0]}]
set_property src_info {type:XDC file:1 line:457 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN T20 [get_ports data_r_s_axi_renable]
set_property src_info {type:XDC file:1 line:464 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {system_i/pblaze_s_0_bram_WE[0]}]]
set_property src_info {type:XDC file:1 line:465 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {system_i/pblaze_s_0_bram_DIN[0]} {system_i/pblaze_s_0_bram_DIN[1]} {system_i/pblaze_s_0_bram_DIN[2]} {system_i/pblaze_s_0_bram_DIN[3]} {system_i/pblaze_s_0_bram_DIN[4]} {system_i/pblaze_s_0_bram_DIN[5]} {system_i/pblaze_s_0_bram_DIN[6]} {system_i/pblaze_s_0_bram_DIN[7]} {system_i/pblaze_s_0_bram_DIN[8]} {system_i/pblaze_s_0_bram_DIN[9]} {system_i/pblaze_s_0_bram_DIN[10]} {system_i/pblaze_s_0_bram_DIN[11]} {system_i/pblaze_s_0_bram_DIN[12]} {system_i/pblaze_s_0_bram_DIN[13]} {system_i/pblaze_s_0_bram_DIN[14]} {system_i/pblaze_s_0_bram_DIN[15]} {system_i/pblaze_s_0_bram_DIN[16]} {system_i/pblaze_s_0_bram_DIN[17]} {system_i/pblaze_s_0_bram_DIN[18]} {system_i/pblaze_s_0_bram_DIN[19]} {system_i/pblaze_s_0_bram_DIN[20]} {system_i/pblaze_s_0_bram_DIN[21]} {system_i/pblaze_s_0_bram_DIN[22]} {system_i/pblaze_s_0_bram_DIN[23]} {system_i/pblaze_s_0_bram_DIN[24]} {system_i/pblaze_s_0_bram_DIN[25]} {system_i/pblaze_s_0_bram_DIN[26]} {system_i/pblaze_s_0_bram_DIN[27]} {system_i/pblaze_s_0_bram_DIN[28]} {system_i/pblaze_s_0_bram_DIN[29]} {system_i/pblaze_s_0_bram_DIN[30]} {system_i/pblaze_s_0_bram_DIN[31]}]]
set_property src_info {type:XDC file:1 line:466 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list system_i/pblaze_s_0_bram_EN]]
set_property src_info {type:XDC file:1 line:467 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list system_i/pblaze_s_0_pB_rdy]]
set_property src_info {type:XDC file:1 line:525 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[22]}]
set_property src_info {type:XDC file:1 line:526 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[0]}]
set_property src_info {type:XDC file:1 line:527 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[2]}]
set_property src_info {type:XDC file:1 line:528 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[6]}]
set_property src_info {type:XDC file:1 line:529 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[2]}]
set_property src_info {type:XDC file:1 line:530 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[12]}]
set_property src_info {type:XDC file:1 line:531 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[1]}]
set_property src_info {type:XDC file:1 line:532 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[25]}]
set_property src_info {type:XDC file:1 line:533 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[7]}]
set_property src_info {type:XDC file:1 line:534 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[9]}]
set_property src_info {type:XDC file:1 line:535 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[16]}]
set_property src_info {type:XDC file:1 line:536 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[11]}]
set_property src_info {type:XDC file:1 line:537 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[10]}]
set_property src_info {type:XDC file:1 line:538 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[4]}]
set_property src_info {type:XDC file:1 line:539 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[26]}]
set_property src_info {type:XDC file:1 line:540 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[0]}]
set_property src_info {type:XDC file:1 line:541 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[31]}]
set_property src_info {type:XDC file:1 line:542 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[19]}]
set_property src_info {type:XDC file:1 line:543 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[14]}]
set_property src_info {type:XDC file:1 line:544 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[24]}]
set_property src_info {type:XDC file:1 line:545 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[17]}]
set_property src_info {type:XDC file:1 line:546 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[3]}]
set_property src_info {type:XDC file:1 line:547 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[13]}]
set_property src_info {type:XDC file:1 line:548 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[21]}]
set_property src_info {type:XDC file:1 line:549 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[7]}]
set_property src_info {type:XDC file:1 line:550 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[25]}]
set_property src_info {type:XDC file:1 line:551 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[14]}]
set_property src_info {type:XDC file:1 line:552 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[8]}]
set_property src_info {type:XDC file:1 line:553 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[28]}]
set_property src_info {type:XDC file:1 line:554 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[27]}]
set_property src_info {type:XDC file:1 line:555 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[3]}]
set_property src_info {type:XDC file:1 line:556 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[30]}]
set_property src_info {type:XDC file:1 line:557 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[29]}]
set_property src_info {type:XDC file:1 line:558 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[26]}]
set_property src_info {type:XDC file:1 line:559 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[5]}]
set_property src_info {type:XDC file:1 line:560 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[28]}]
set_property src_info {type:XDC file:1 line:561 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[21]}]
set_property src_info {type:XDC file:1 line:562 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[18]}]
set_property src_info {type:XDC file:1 line:563 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[18]}]
set_property src_info {type:XDC file:1 line:564 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[17]}]
set_property src_info {type:XDC file:1 line:565 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[20]}]
set_property src_info {type:XDC file:1 line:566 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[20]}]
set_property src_info {type:XDC file:1 line:567 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[6]}]
set_property src_info {type:XDC file:1 line:568 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[15]}]
set_property src_info {type:XDC file:1 line:569 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[5]}]
set_property src_info {type:XDC file:1 line:570 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[4]}]
set_property src_info {type:XDC file:1 line:571 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[19]}]
set_property src_info {type:XDC file:1 line:572 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[24]}]
set_property src_info {type:XDC file:1 line:573 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[23]}]
set_property src_info {type:XDC file:1 line:574 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[1]}]
set_property src_info {type:XDC file:1 line:575 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[10]}]
set_property src_info {type:XDC file:1 line:576 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[15]}]
set_property src_info {type:XDC file:1 line:577 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[16]}]
set_property src_info {type:XDC file:1 line:578 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[22]}]
set_property src_info {type:XDC file:1 line:579 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[29]}]
set_property src_info {type:XDC file:1 line:580 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[9]}]
set_property src_info {type:XDC file:1 line:581 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[23]}]
set_property src_info {type:XDC file:1 line:582 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[30]}]
set_property src_info {type:XDC file:1 line:583 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addra[31]}]
set_property src_info {type:XDC file:1 line:584 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[13]}]
set_property src_info {type:XDC file:1 line:585 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[8]}]
set_property src_info {type:XDC file:1 line:586 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[12]}]
set_property src_info {type:XDC file:1 line:587 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[11]}]
set_property src_info {type:XDC file:1 line:588 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/addrb[27]}]
set_property src_info {type:XDC file:1 line:597 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[7]}]
set_property src_info {type:XDC file:1 line:599 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[25]}]
set_property src_info {type:XDC file:1 line:601 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[15]}]
set_property src_info {type:XDC file:1 line:603 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[17]}]
set_property src_info {type:XDC file:1 line:605 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[12]}]
set_property src_info {type:XDC file:1 line:609 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[18]}]
set_property src_info {type:XDC file:1 line:611 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[5]}]
set_property src_info {type:XDC file:1 line:612 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[16]}]
set_property src_info {type:XDC file:1 line:615 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[16]}]
set_property src_info {type:XDC file:1 line:617 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[8]}]
set_property src_info {type:XDC file:1 line:618 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[14]}]
set_property src_info {type:XDC file:1 line:621 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[11]}]
set_property src_info {type:XDC file:1 line:622 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[22]}]
set_property src_info {type:XDC file:1 line:625 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[0]}]
set_property src_info {type:XDC file:1 line:630 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[7]}]
set_property src_info {type:XDC file:1 line:631 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[26]}]
set_property src_info {type:XDC file:1 line:632 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[1]}]
set_property src_info {type:XDC file:1 line:633 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[19]}]
set_property src_info {type:XDC file:1 line:634 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[30]}]
set_property src_info {type:XDC file:1 line:635 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[2]}]
set_property src_info {type:XDC file:1 line:640 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[29]}]
set_property src_info {type:XDC file:1 line:641 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[15]}]
set_property src_info {type:XDC file:1 line:642 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[21]}]
set_property src_info {type:XDC file:1 line:643 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[26]}]
set_property src_info {type:XDC file:1 line:644 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[28]}]
set_property src_info {type:XDC file:1 line:645 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[6]}]
set_property src_info {type:XDC file:1 line:649 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[3]}]
set_property src_info {type:XDC file:1 line:650 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[10]}]
set_property src_info {type:XDC file:1 line:651 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[29]}]
set_property src_info {type:XDC file:1 line:657 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[13]}]
set_property src_info {type:XDC file:1 line:658 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[5]}]
set_property src_info {type:XDC file:1 line:659 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[3]}]
set_property src_info {type:XDC file:1 line:666 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[27]}]
set_property src_info {type:XDC file:1 line:667 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[2]}]
set_property src_info {type:XDC file:1 line:669 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[9]}]
set_property src_info {type:XDC file:1 line:677 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[6]}]
set_property src_info {type:XDC file:1 line:678 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[12]}]
set_property src_info {type:XDC file:1 line:679 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[23]}]
set_property src_info {type:XDC file:1 line:680 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[1]}]
set_property src_info {type:XDC file:1 line:681 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[18]}]
set_property src_info {type:XDC file:1 line:688 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[0]}]
set_property src_info {type:XDC file:1 line:690 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[19]}]
set_property src_info {type:XDC file:1 line:694 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[11]}]
set_property src_info {type:XDC file:1 line:695 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[9]}]
set_property src_info {type:XDC file:1 line:696 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[17]}]
set_property src_info {type:XDC file:1 line:697 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[25]}]
set_property src_info {type:XDC file:1 line:698 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[24]}]
set_property src_info {type:XDC file:1 line:699 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[31]}]
set_property src_info {type:XDC file:1 line:700 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[14]}]
set_property src_info {type:XDC file:1 line:701 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[30]}]
set_property src_info {type:XDC file:1 line:702 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[4]}]
set_property src_info {type:XDC file:1 line:703 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[8]}]
set_property src_info {type:XDC file:1 line:704 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/doutb[20]}]
set_property src_info {type:XDC file:1 line:705 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[20]}]
set_property src_info {type:XDC file:1 line:706 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[13]}]
set_property src_info {type:XDC file:1 line:707 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[31]}]
set_property src_info {type:XDC file:1 line:708 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[24]}]
set_property src_info {type:XDC file:1 line:709 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[28]}]
set_property src_info {type:XDC file:1 line:710 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[22]}]
set_property src_info {type:XDC file:1 line:711 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[27]}]
set_property src_info {type:XDC file:1 line:712 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[23]}]
set_property src_info {type:XDC file:1 line:713 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[21]}]
set_property src_info {type:XDC file:1 line:714 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[4]}]
set_property src_info {type:XDC file:1 line:715 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_bram/douta[10]}]
set_property src_info {type:XDC file:1 line:732 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/pblaze_m_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/reset]
set_property src_info {type:XDC file:1 line:781 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG false [get_nets system_i/pblaze_m_0/U0/pBlaze_v1_0_S_AXI_inst/Proccesor_v1/reset0]
