# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/xup/fpga_flow/TFMV2/TFM_GE/TFM_GE.srcs/sources_1/bd/system/ip/system_pblaze_s_1_1/system_pblaze_s_1_1.xci
# IP: The module: 'system_pblaze_s_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/xup/fpga_flow/TFMV2/TFM_GE/TFM_GE.srcs/sources_1/bd/system/ip/system_pblaze_s_1_1/ip/mult_gen_0/mult_gen_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0}]

# IP: c:/xup/fpga_flow/TFMV2/TFM_GE/TFM_GE.srcs/sources_1/bd/system/ip/system_pblaze_s_1_1/system_pblaze_s_1_1.xci
# IP: The module: 'system_pblaze_s_1_1' is the root of the design. Do not add the DONT_TOUCH constraint.

# IP: c:/xup/fpga_flow/TFMV2/TFM_GE/TFM_GE.srcs/sources_1/bd/system/ip/system_pblaze_s_1_1/ip/mult_gen_0/mult_gen_0.xci
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==mult_gen_0 || ORIG_REF_NAME==mult_gen_0}]
