# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/sol_v1/sol_v1.srcs/sources_1/bd/system/ip/system_axi_cdma_0_0/system_axi_cdma_0_0.xci
# IP: The module: 'system_axi_cdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/sol_v1/sol_v1.srcs/sources_1/bd/system/ip/system_axi_cdma_0_0/system_axi_cdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_cdma_0_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/sol_v1/sol_v1.srcs/sources_1/bd/system/ip/system_axi_cdma_0_0/system_axi_cdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_cdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# IP: c:/xup/fpga_flow/2016_2_zynq_labs/sol_v1/sol_v1.srcs/sources_1/bd/system/ip/system_axi_cdma_0_0/system_axi_cdma_0_0.xci
# IP: The module: 'system_axi_cdma_0_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/sol_v1/sol_v1.srcs/sources_1/bd/system/ip/system_axi_cdma_0_0/system_axi_cdma_0_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_cdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]

# XDC: c:/xup/fpga_flow/2016_2_zynq_labs/sol_v1/sol_v1.srcs/sources_1/bd/system/ip/system_axi_cdma_0_0/system_axi_cdma_0_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'system_axi_cdma_0_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0]
