set_property SRC_FILE_INFO {cfile:C:/xup/fpga_flow/2016_2_zynq_labs/sol_v1/sol_v1.srcs/constrs_1/imports/Desktop/zybo.xdc rfile:../../../sol_v1.srcs/constrs_1/imports/Desktop/zybo.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:4 export:INPUT save:INPUT read:READ} [current_design]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports {btn_tri_io[0]}]
set_property src_info {type:XDC file:1 line:157 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[2]}]
set_property src_info {type:XDC file:1 line:158 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[6]}]
set_property src_info {type:XDC file:1 line:159 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[3]}]
set_property src_info {type:XDC file:1 line:160 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[5]}]
set_property src_info {type:XDC file:1 line:161 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[7]}]
set_property src_info {type:XDC file:1 line:162 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[1]}]
set_property src_info {type:XDC file:1 line:163 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[0]}]
set_property src_info {type:XDC file:1 line:164 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[4]}]
set_property src_info {type:XDC file:1 line:165 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[3]}]
set_property src_info {type:XDC file:1 line:166 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[7]}]
set_property src_info {type:XDC file:1 line:167 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[5]}]
set_property src_info {type:XDC file:1 line:168 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[1]}]
set_property src_info {type:XDC file:1 line:169 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[2]}]
set_property src_info {type:XDC file:1 line:170 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[6]}]
set_property src_info {type:XDC file:1 line:171 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[4]}]
set_property src_info {type:XDC file:1 line:172 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[0]}]
set_property src_info {type:XDC file:1 line:173 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/reset0]
set_property src_info {type:XDC file:1 line:174 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/reset_reg_n_0]
set_property src_info {type:XDC file:1 line:175 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[4]}]
set_property src_info {type:XDC file:1 line:176 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[0]}]
set_property src_info {type:XDC file:1 line:177 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[7]}]
set_property src_info {type:XDC file:1 line:178 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[3]}]
set_property src_info {type:XDC file:1 line:179 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[1]}]
set_property src_info {type:XDC file:1 line:180 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[2]}]
set_property src_info {type:XDC file:1 line:181 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[5]}]
set_property src_info {type:XDC file:1 line:182 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[6]}]
set_property src_info {type:XDC file:1 line:183 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/reset_reg]
set_property src_info {type:XDC file:1 line:186 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe71 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/reset_reg_n_0]]
set_property src_info {type:XDC file:1 line:194 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_5]
set_property src_info {type:XDC file:1 line:195 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_1]
set_property src_info {type:XDC file:1 line:196 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_0]
set_property src_info {type:XDC file:1 line:197 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_4]
set_property src_info {type:XDC file:1 line:198 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_3]
set_property src_info {type:XDC file:1 line:199 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_2]
set_property src_info {type:XDC file:1 line:200 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_6]
set_property src_info {type:XDC file:1 line:201 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_7]
set_property src_info {type:XDC file:1 line:203 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/pB_rdy]
set_property src_info {type:XDC file:1 line:204 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/s_axi_araddr[2]}]
set_property src_info {type:XDC file:1 line:205 export:INPUT save:INPUT read:READ} [current_design]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/s_axi_araddr[3]}]
set_property src_info {type:XDC file:1 line:206 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[0]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[1]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[2]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[3]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[4]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[5]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[6]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[7]}]]
set_property src_info {type:XDC file:1 line:207 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe43 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/reset_reg]]
set_property src_info {type:XDC file:1 line:211 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe42 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/reset0]]
set_property src_info {type:XDC file:1 line:213 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe42 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_0]]
set_property src_info {type:XDC file:1 line:214 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe43 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_1]]
set_property src_info {type:XDC file:1 line:215 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe44 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_2]]
set_property src_info {type:XDC file:1 line:216 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe45 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_3]]
set_property src_info {type:XDC file:1 line:217 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe46 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_4]]
set_property src_info {type:XDC file:1 line:218 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe47 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_5]]
set_property src_info {type:XDC file:1 line:219 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe48 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_6]]
set_property src_info {type:XDC file:1 line:220 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe49 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_7]]
set_property src_info {type:XDC file:1 line:223 export:INPUT save:INPUT read:READ} [current_design]
create_debug_core u_ila_0 ila
set_property src_info {type:XDC file:1 line:224 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:225 export:INPUT save:INPUT read:READ} [current_design]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:226 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:227 export:INPUT save:INPUT read:READ} [current_design]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:228 export:INPUT save:INPUT read:READ} [current_design]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:229 export:INPUT save:INPUT read:READ} [current_design]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:230 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:231 export:INPUT save:INPUT read:READ} [current_design]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property src_info {type:XDC file:1 line:232 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
set_property src_info {type:XDC file:1 line:233 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/clk [get_nets [list system_i/processing_system7_0/inst/FCLK_CLK0]]
set_property src_info {type:XDC file:1 line:234 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:235 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
set_property src_info {type:XDC file:1 line:236 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe0 [get_nets [list {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[0]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[1]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[2]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[3]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[4]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[5]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[6]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[7]}]]
set_property src_info {type:XDC file:1 line:237 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:238 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:239 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
set_property src_info {type:XDC file:1 line:240 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[0]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[1]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[2]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[3]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[4]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[5]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[6]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[7]}]]
set_property src_info {type:XDC file:1 line:241 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:242 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:243 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 2 [get_debug_ports u_ila_0/probe2]
set_property src_info {type:XDC file:1 line:244 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe2 [get_nets [list {system_i/pBlaze_0/s_axi_araddr[2]} {system_i/pBlaze_0/s_axi_araddr[3]}]]
set_property src_info {type:XDC file:1 line:245 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:246 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:247 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
set_property src_info {type:XDC file:1 line:248 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe3 [get_nets [list {system_i/ps7_0_axi_periph_M00_AXI_WDATA[0]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[1]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[2]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[3]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[4]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[5]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[6]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[7]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[8]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[9]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[10]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[11]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[12]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[13]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[14]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[15]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[16]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[17]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[18]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[19]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[20]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[21]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[22]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[23]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[24]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[25]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[26]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[27]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[28]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[29]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[30]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[31]}]]
set_property src_info {type:XDC file:1 line:249 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:250 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:251 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
set_property src_info {type:XDC file:1 line:252 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe4 [get_nets [list {system_i/ps7_0_axi_periph_M00_AXI_RDATA[0]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[1]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[2]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[3]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[4]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[5]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[6]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[7]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[8]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[9]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[10]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[11]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[12]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[13]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[14]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[15]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[16]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[17]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[18]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[19]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[20]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[21]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[22]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[23]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[24]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[25]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[26]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[27]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[28]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[29]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[30]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[31]}]]
set_property src_info {type:XDC file:1 line:253 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:254 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:255 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe5]
set_property src_info {type:XDC file:1 line:256 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe5 [get_nets [list {system_i/ps7_0_axi_periph_M00_AXI_AWADDR[0]} {system_i/ps7_0_axi_periph_M00_AXI_AWADDR[1]} {system_i/ps7_0_axi_periph_M00_AXI_AWADDR[2]} {system_i/ps7_0_axi_periph_M00_AXI_AWADDR[3]}]]
set_property src_info {type:XDC file:1 line:257 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:258 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:259 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 4 [get_debug_ports u_ila_0/probe6]
set_property src_info {type:XDC file:1 line:260 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe6 [get_nets [list {system_i/ps7_0_axi_periph_M00_AXI_ARADDR[0]} {system_i/ps7_0_axi_periph_M00_AXI_ARADDR[1]} {system_i/ps7_0_axi_periph_M00_AXI_ARADDR[2]} {system_i/ps7_0_axi_periph_M00_AXI_ARADDR[3]}]]
set_property src_info {type:XDC file:1 line:261 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:262 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:263 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 12 [get_debug_ports u_ila_0/probe7]
set_property src_info {type:XDC file:1 line:264 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe7 [get_nets [list {system_i/pBlaze_0_address[2]} {system_i/pBlaze_0_address[3]} {system_i/pBlaze_0_address[4]} {system_i/pBlaze_0_address[5]} {system_i/pBlaze_0_address[6]} {system_i/pBlaze_0_address[7]} {system_i/pBlaze_0_address[8]} {system_i/pBlaze_0_address[9]} {system_i/pBlaze_0_address[10]} {system_i/pBlaze_0_address[11]} {system_i/pBlaze_0_address[12]} {system_i/pBlaze_0_address[13]}]]
set_property src_info {type:XDC file:1 line:265 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:266 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:267 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 18 [get_debug_ports u_ila_0/probe8]
set_property src_info {type:XDC file:1 line:268 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe8 [get_nets [list {system_i/axi_bram_ctrl_0_bram_doutb[0]} {system_i/axi_bram_ctrl_0_bram_doutb[1]} {system_i/axi_bram_ctrl_0_bram_doutb[2]} {system_i/axi_bram_ctrl_0_bram_doutb[3]} {system_i/axi_bram_ctrl_0_bram_doutb[4]} {system_i/axi_bram_ctrl_0_bram_doutb[5]} {system_i/axi_bram_ctrl_0_bram_doutb[6]} {system_i/axi_bram_ctrl_0_bram_doutb[7]} {system_i/axi_bram_ctrl_0_bram_doutb[8]} {system_i/axi_bram_ctrl_0_bram_doutb[9]} {system_i/axi_bram_ctrl_0_bram_doutb[10]} {system_i/axi_bram_ctrl_0_bram_doutb[11]} {system_i/axi_bram_ctrl_0_bram_doutb[12]} {system_i/axi_bram_ctrl_0_bram_doutb[13]} {system_i/axi_bram_ctrl_0_bram_doutb[14]} {system_i/axi_bram_ctrl_0_bram_doutb[15]} {system_i/axi_bram_ctrl_0_bram_doutb[16]} {system_i/axi_bram_ctrl_0_bram_doutb[17]}]]
set_property src_info {type:XDC file:1 line:269 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:270 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:271 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
set_property src_info {type:XDC file:1 line:272 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe9 [get_nets [list {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[0]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[1]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[2]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[3]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[4]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[5]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[6]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[7]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[8]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[9]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[10]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[11]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[12]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[13]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[14]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[15]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[16]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[17]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[18]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[19]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[20]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[21]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[22]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[23]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[24]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[25]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[26]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[27]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[28]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[29]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[30]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[31]}]]
set_property src_info {type:XDC file:1 line:273 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:274 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:275 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 14 [get_debug_ports u_ila_0/probe10]
set_property src_info {type:XDC file:1 line:276 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe10 [get_nets [list {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[2]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[3]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[4]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[5]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[6]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[7]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[8]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[9]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[10]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[11]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[12]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[13]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[14]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[15]}]]
set_property src_info {type:XDC file:1 line:277 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:278 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:279 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
set_property src_info {type:XDC file:1 line:280 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe11 [get_nets [list system_i/axi_bram_ctrl_0_BRAM_PORTA_EN]]
set_property src_info {type:XDC file:1 line:281 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:282 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:283 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
set_property src_info {type:XDC file:1 line:284 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe12 [get_nets [list system_i/pBlaze_0/pB_rdy]]
set_property src_info {type:XDC file:1 line:285 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:286 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:287 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
set_property src_info {type:XDC file:1 line:288 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe13 [get_nets [list system_i/pBlaze_0_ram_enable]]
set_property src_info {type:XDC file:1 line:289 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:290 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:291 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
set_property src_info {type:XDC file:1 line:292 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe14 [get_nets [list system_i/ps7_0_axi_periph_n_36]]
set_property src_info {type:XDC file:1 line:293 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:294 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:295 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
set_property src_info {type:XDC file:1 line:296 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe15 [get_nets [list system_i/ps7_0_axi_periph_n_37]]
set_property src_info {type:XDC file:1 line:297 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:298 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:299 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
set_property src_info {type:XDC file:1 line:300 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe16 [get_nets [list system_i/ps7_0_axi_periph_n_38]]
set_property src_info {type:XDC file:1 line:301 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:302 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:303 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
set_property src_info {type:XDC file:1 line:304 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe17 [get_nets [list system_i/ps7_0_axi_periph_n_39]]
set_property src_info {type:XDC file:1 line:305 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:306 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:307 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
set_property src_info {type:XDC file:1 line:308 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe18 [get_nets [list system_i/ps7_0_axi_periph_n_40]]
set_property src_info {type:XDC file:1 line:309 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:310 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:311 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
set_property src_info {type:XDC file:1 line:312 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe19 [get_nets [list system_i/ps7_0_axi_periph_n_41]]
set_property src_info {type:XDC file:1 line:313 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:314 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:315 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
set_property src_info {type:XDC file:1 line:316 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe20 [get_nets [list system_i/ps7_0_axi_periph_n_42]]
set_property src_info {type:XDC file:1 line:317 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:318 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:319 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
set_property src_info {type:XDC file:1 line:320 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe21 [get_nets [list system_i/ps7_0_axi_periph_n_43]]
set_property src_info {type:XDC file:1 line:321 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:322 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:1 line:323 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
set_property src_info {type:XDC file:1 line:324 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe22 [get_nets [list system_i/ps7_0_axi_periph_n_44]]
set_property src_info {type:XDC file:1 line:325 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:326 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:1 line:327 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
set_property src_info {type:XDC file:1 line:328 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe23 [get_nets [list system_i/ps7_0_axi_periph_n_45]]
set_property src_info {type:XDC file:1 line:329 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:330 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:1 line:331 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
set_property src_info {type:XDC file:1 line:332 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe24 [get_nets [list system_i/ps7_0_axi_periph_n_46]]
set_property src_info {type:XDC file:1 line:333 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:334 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:1 line:335 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
set_property src_info {type:XDC file:1 line:336 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe25 [get_nets [list system_i/ps7_0_axi_periph_n_47]]
set_property src_info {type:XDC file:1 line:337 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:338 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:1 line:339 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
set_property src_info {type:XDC file:1 line:340 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe26 [get_nets [list system_i/ps7_0_axi_periph_n_48]]
set_property src_info {type:XDC file:1 line:341 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:342 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:1 line:343 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
set_property src_info {type:XDC file:1 line:344 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe27 [get_nets [list system_i/ps7_0_axi_periph_n_49]]
set_property src_info {type:XDC file:1 line:345 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:346 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:1 line:347 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
set_property src_info {type:XDC file:1 line:348 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe28 [get_nets [list system_i/ps7_0_axi_periph_n_50]]
set_property src_info {type:XDC file:1 line:349 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:350 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property src_info {type:XDC file:1 line:351 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
set_property src_info {type:XDC file:1 line:352 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe29 [get_nets [list system_i/ps7_0_axi_periph_n_51]]
set_property src_info {type:XDC file:1 line:353 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:354 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property src_info {type:XDC file:1 line:355 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
set_property src_info {type:XDC file:1 line:356 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe30 [get_nets [list system_i/ps7_0_axi_periph_n_52]]
set_property src_info {type:XDC file:1 line:357 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:358 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property src_info {type:XDC file:1 line:359 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
set_property src_info {type:XDC file:1 line:360 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe31 [get_nets [list system_i/ps7_0_axi_periph_n_53]]
set_property src_info {type:XDC file:1 line:361 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:362 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property src_info {type:XDC file:1 line:363 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
set_property src_info {type:XDC file:1 line:364 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe32 [get_nets [list system_i/ps7_0_axi_periph_n_54]]
set_property src_info {type:XDC file:1 line:365 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:366 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property src_info {type:XDC file:1 line:367 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
set_property src_info {type:XDC file:1 line:368 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe33 [get_nets [list system_i/ps7_0_axi_periph_n_55]]
set_property src_info {type:XDC file:1 line:369 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:370 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property src_info {type:XDC file:1 line:371 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
set_property src_info {type:XDC file:1 line:372 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe34 [get_nets [list system_i/ps7_0_axi_periph_n_56]]
set_property src_info {type:XDC file:1 line:373 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:374 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property src_info {type:XDC file:1 line:375 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
set_property src_info {type:XDC file:1 line:376 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe35 [get_nets [list system_i/ps7_0_axi_periph_n_57]]
set_property src_info {type:XDC file:1 line:377 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:378 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property src_info {type:XDC file:1 line:379 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
set_property src_info {type:XDC file:1 line:380 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe36 [get_nets [list system_i/ps7_0_axi_periph_n_58]]
set_property src_info {type:XDC file:1 line:381 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:382 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property src_info {type:XDC file:1 line:383 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
set_property src_info {type:XDC file:1 line:384 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe37 [get_nets [list system_i/ps7_0_axi_periph_n_59]]
set_property src_info {type:XDC file:1 line:385 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:386 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property src_info {type:XDC file:1 line:387 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
set_property src_info {type:XDC file:1 line:388 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe38 [get_nets [list system_i/ps7_0_axi_periph_n_60]]
set_property src_info {type:XDC file:1 line:389 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:390 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property src_info {type:XDC file:1 line:391 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
set_property src_info {type:XDC file:1 line:392 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe39 [get_nets [list system_i/ps7_0_axi_periph_n_61]]
set_property src_info {type:XDC file:1 line:393 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:394 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property src_info {type:XDC file:1 line:395 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
set_property src_info {type:XDC file:1 line:396 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe40 [get_nets [list system_i/ps7_0_axi_periph_n_62]]
set_property src_info {type:XDC file:1 line:397 export:INPUT save:INPUT read:READ} [current_design]
create_debug_port u_ila_0 probe
set_property src_info {type:XDC file:1 line:398 export:INPUT save:INPUT read:READ} [current_design]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property src_info {type:XDC file:1 line:399 export:INPUT save:INPUT read:READ} [current_design]
set_property port_width 1 [get_debug_ports u_ila_0/probe41]
set_property src_info {type:XDC file:1 line:400 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port u_ila_0/probe41 [get_nets [list system_i/ps7_0_axi_periph_n_63]]
set_property src_info {type:XDC file:1 line:401 export:INPUT save:INPUT read:READ} [current_design]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:402 export:INPUT save:INPUT read:READ} [current_design]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:403 export:INPUT save:INPUT read:READ} [current_design]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
set_property src_info {type:XDC file:1 line:404 export:INPUT save:INPUT read:READ} [current_design]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
