#set_property PACKAGE_PIN Y16 [get_ports {btn_tri_io[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {btn_tri_io[0]}]
#set_property -dict {PACKAGE_PIN M14 IOSTANDARD LVCMOS33} [get_ports pB_rdy]
set_property -dict {PACKAGE_PIN N15 IOSTANDARD LVCMOS33} [get_ports {btn_tri_io[0]}]


set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[2]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[15]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[8]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[11]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[14]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[6]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[10]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[9]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[5]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[4]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[12]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[3]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[7]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[13]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[2]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[22]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[7]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[0]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[1]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[25]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[9]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[15]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[10]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[6]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[13]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[4]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[23]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[8]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[20]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[21]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[5]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[27]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[12]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[18]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[19]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[29]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[24]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[31]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[30]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[28]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[17]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[14]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[16]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[3]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[26]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[11]}]
set_property MARK_DEBUG true [get_nets system_i/axi_bram_ctrl_0_BRAM_PORTA_EN]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0_ram_enable]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[2]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[16]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[5]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[15]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[6]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[8]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[11]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[14]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[17]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[3]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[12]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[7]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[0]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[13]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[4]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[9]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[10]}]
set_property MARK_DEBUG true [get_nets {system_i/axi_bram_ctrl_0_bram_doutb[1]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0_address[12]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0_address[10]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0_address[4]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0_address[3]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0_address[8]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0_address[7]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0_address[6]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0_address[2]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0_address[5]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0_address[11]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0_address[9]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0_address[13]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_ARADDR[2]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_ARADDR[3]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_ARADDR[0]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_ARADDR[1]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_AWADDR[2]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_AWADDR[1]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_AWADDR[0]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_AWADDR[3]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[3]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[31]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[6]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[0]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[28]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[23]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[22]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[4]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[27]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[2]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[8]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[7]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[13]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[1]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[12]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[30]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[15]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[24]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[10]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[9]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[11]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[5]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[14]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[29]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[25]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[19]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[20]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[26]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[16]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[17]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[18]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_WDATA[21]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[24]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[26]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[0]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[11]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[15]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[30]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[1]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[6]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[12]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[29]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[3]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[23]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[25]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[31]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[27]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[19]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[13]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[4]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[9]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[22]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[2]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[5]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[7]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[14]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[8]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[20]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[17]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[18]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[21]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[28]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[16]}]
set_property MARK_DEBUG true [get_nets {system_i/ps7_0_axi_periph_M00_AXI_RDATA[10]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[2]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[6]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[3]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[5]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[7]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[1]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[0]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[4]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[3]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[7]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[5]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[1]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[2]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[6]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[4]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[0]}]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/reset0]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/reset_reg_n_0]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[4]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[0]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[7]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[3]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[1]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[2]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[5]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[6]}]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/reset_reg]


connect_debug_port u_ila_0/probe71 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/reset_reg_n_0]]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0_address[1]}]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[1]}]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0_address[14]}]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0_address[15]}]
set_property MARK_DEBUG false [get_nets {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[0]}]
set_property MARK_DEBUG false [get_nets {system_i/pBlaze_0_address[0]}]

set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_5]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_1]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_0]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_4]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_3]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_2]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_6]
set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_7]

set_property MARK_DEBUG true [get_nets system_i/pBlaze_0/pB_rdy]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/s_axi_araddr[2]}]
set_property MARK_DEBUG true [get_nets {system_i/pBlaze_0/s_axi_araddr[3]}]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[0]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[1]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[2]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[3]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[4]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[5]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[6]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/out_reg0[7]}]]
connect_debug_port u_ila_0/probe43 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/reset_reg]]



connect_debug_port u_ila_0/probe42 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/reset0]]

connect_debug_port u_ila_0/probe42 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_0]]
connect_debug_port u_ila_0/probe43 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_1]]
connect_debug_port u_ila_0/probe44 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_2]]
connect_debug_port u_ila_0/probe45 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_3]]
connect_debug_port u_ila_0/probe46 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_4]]
connect_debug_port u_ila_0/probe47 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_5]]
connect_debug_port u_ila_0/probe48 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_6]]
connect_debug_port u_ila_0/probe49 [get_nets [list system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/sy_or_kk_7]]


create_debug_core u_ila_0 ila
set_property ALL_PROBE_SAME_MU true [get_debug_cores u_ila_0]
set_property ALL_PROBE_SAME_MU_CNT 1 [get_debug_cores u_ila_0]
set_property C_ADV_TRIGGER false [get_debug_cores u_ila_0]
set_property C_DATA_DEPTH 1024 [get_debug_cores u_ila_0]
set_property C_EN_STRG_QUAL false [get_debug_cores u_ila_0]
set_property C_INPUT_PIPE_STAGES 0 [get_debug_cores u_ila_0]
set_property C_TRIGIN_EN false [get_debug_cores u_ila_0]
set_property C_TRIGOUT_EN false [get_debug_cores u_ila_0]
set_property port_width 1 [get_debug_ports u_ila_0/clk]
connect_debug_port u_ila_0/clk [get_nets [list system_i/processing_system7_0/inst/FCLK_CLK0]]
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe0]
set_property port_width 8 [get_debug_ports u_ila_0/probe0]
connect_debug_port u_ila_0/probe0 [get_nets [list {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[0]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[1]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[2]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[3]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[4]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[5]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[6]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/kcpsm6_v1/out_port[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe1]
set_property port_width 8 [get_debug_ports u_ila_0/probe1]
connect_debug_port u_ila_0/probe1 [get_nets [list {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[0]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[1]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[2]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[3]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[4]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[5]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[6]} {system_i/pBlaze_0/U0/picoBlaze_v1_0_S_AXI_inst/Proccesor_v1/in_port[7]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe2]
set_property port_width 2 [get_debug_ports u_ila_0/probe2]
connect_debug_port u_ila_0/probe2 [get_nets [list {system_i/pBlaze_0/s_axi_araddr[2]} {system_i/pBlaze_0/s_axi_araddr[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe3]
set_property port_width 32 [get_debug_ports u_ila_0/probe3]
connect_debug_port u_ila_0/probe3 [get_nets [list {system_i/ps7_0_axi_periph_M00_AXI_WDATA[0]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[1]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[2]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[3]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[4]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[5]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[6]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[7]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[8]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[9]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[10]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[11]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[12]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[13]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[14]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[15]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[16]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[17]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[18]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[19]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[20]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[21]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[22]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[23]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[24]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[25]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[26]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[27]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[28]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[29]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[30]} {system_i/ps7_0_axi_periph_M00_AXI_WDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe4]
set_property port_width 32 [get_debug_ports u_ila_0/probe4]
connect_debug_port u_ila_0/probe4 [get_nets [list {system_i/ps7_0_axi_periph_M00_AXI_RDATA[0]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[1]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[2]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[3]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[4]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[5]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[6]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[7]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[8]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[9]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[10]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[11]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[12]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[13]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[14]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[15]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[16]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[17]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[18]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[19]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[20]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[21]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[22]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[23]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[24]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[25]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[26]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[27]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[28]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[29]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[30]} {system_i/ps7_0_axi_periph_M00_AXI_RDATA[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe5]
set_property port_width 4 [get_debug_ports u_ila_0/probe5]
connect_debug_port u_ila_0/probe5 [get_nets [list {system_i/ps7_0_axi_periph_M00_AXI_AWADDR[0]} {system_i/ps7_0_axi_periph_M00_AXI_AWADDR[1]} {system_i/ps7_0_axi_periph_M00_AXI_AWADDR[2]} {system_i/ps7_0_axi_periph_M00_AXI_AWADDR[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe6]
set_property port_width 4 [get_debug_ports u_ila_0/probe6]
connect_debug_port u_ila_0/probe6 [get_nets [list {system_i/ps7_0_axi_periph_M00_AXI_ARADDR[0]} {system_i/ps7_0_axi_periph_M00_AXI_ARADDR[1]} {system_i/ps7_0_axi_periph_M00_AXI_ARADDR[2]} {system_i/ps7_0_axi_periph_M00_AXI_ARADDR[3]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe7]
set_property port_width 12 [get_debug_ports u_ila_0/probe7]
connect_debug_port u_ila_0/probe7 [get_nets [list {system_i/pBlaze_0_address[2]} {system_i/pBlaze_0_address[3]} {system_i/pBlaze_0_address[4]} {system_i/pBlaze_0_address[5]} {system_i/pBlaze_0_address[6]} {system_i/pBlaze_0_address[7]} {system_i/pBlaze_0_address[8]} {system_i/pBlaze_0_address[9]} {system_i/pBlaze_0_address[10]} {system_i/pBlaze_0_address[11]} {system_i/pBlaze_0_address[12]} {system_i/pBlaze_0_address[13]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe8]
set_property port_width 18 [get_debug_ports u_ila_0/probe8]
connect_debug_port u_ila_0/probe8 [get_nets [list {system_i/axi_bram_ctrl_0_bram_doutb[0]} {system_i/axi_bram_ctrl_0_bram_doutb[1]} {system_i/axi_bram_ctrl_0_bram_doutb[2]} {system_i/axi_bram_ctrl_0_bram_doutb[3]} {system_i/axi_bram_ctrl_0_bram_doutb[4]} {system_i/axi_bram_ctrl_0_bram_doutb[5]} {system_i/axi_bram_ctrl_0_bram_doutb[6]} {system_i/axi_bram_ctrl_0_bram_doutb[7]} {system_i/axi_bram_ctrl_0_bram_doutb[8]} {system_i/axi_bram_ctrl_0_bram_doutb[9]} {system_i/axi_bram_ctrl_0_bram_doutb[10]} {system_i/axi_bram_ctrl_0_bram_doutb[11]} {system_i/axi_bram_ctrl_0_bram_doutb[12]} {system_i/axi_bram_ctrl_0_bram_doutb[13]} {system_i/axi_bram_ctrl_0_bram_doutb[14]} {system_i/axi_bram_ctrl_0_bram_doutb[15]} {system_i/axi_bram_ctrl_0_bram_doutb[16]} {system_i/axi_bram_ctrl_0_bram_doutb[17]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe9]
set_property port_width 32 [get_debug_ports u_ila_0/probe9]
connect_debug_port u_ila_0/probe9 [get_nets [list {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[0]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[1]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[2]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[3]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[4]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[5]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[6]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[7]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[8]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[9]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[10]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[11]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[12]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[13]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[14]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[15]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[16]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[17]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[18]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[19]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[20]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[21]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[22]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[23]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[24]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[25]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[26]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[27]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[28]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[29]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[30]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_DIN[31]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe10]
set_property port_width 14 [get_debug_ports u_ila_0/probe10]
connect_debug_port u_ila_0/probe10 [get_nets [list {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[2]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[3]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[4]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[5]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[6]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[7]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[8]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[9]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[10]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[11]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[12]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[13]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[14]} {system_i/axi_bram_ctrl_0_BRAM_PORTA_ADDR[15]}]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe11]
set_property port_width 1 [get_debug_ports u_ila_0/probe11]
connect_debug_port u_ila_0/probe11 [get_nets [list system_i/axi_bram_ctrl_0_BRAM_PORTA_EN]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe12]
set_property port_width 1 [get_debug_ports u_ila_0/probe12]
connect_debug_port u_ila_0/probe12 [get_nets [list system_i/pBlaze_0/pB_rdy]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe13]
set_property port_width 1 [get_debug_ports u_ila_0/probe13]
connect_debug_port u_ila_0/probe13 [get_nets [list system_i/pBlaze_0_ram_enable]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe14]
set_property port_width 1 [get_debug_ports u_ila_0/probe14]
connect_debug_port u_ila_0/probe14 [get_nets [list system_i/ps7_0_axi_periph_n_36]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe15]
set_property port_width 1 [get_debug_ports u_ila_0/probe15]
connect_debug_port u_ila_0/probe15 [get_nets [list system_i/ps7_0_axi_periph_n_37]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe16]
set_property port_width 1 [get_debug_ports u_ila_0/probe16]
connect_debug_port u_ila_0/probe16 [get_nets [list system_i/ps7_0_axi_periph_n_38]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe17]
set_property port_width 1 [get_debug_ports u_ila_0/probe17]
connect_debug_port u_ila_0/probe17 [get_nets [list system_i/ps7_0_axi_periph_n_39]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe18]
set_property port_width 1 [get_debug_ports u_ila_0/probe18]
connect_debug_port u_ila_0/probe18 [get_nets [list system_i/ps7_0_axi_periph_n_40]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe19]
set_property port_width 1 [get_debug_ports u_ila_0/probe19]
connect_debug_port u_ila_0/probe19 [get_nets [list system_i/ps7_0_axi_periph_n_41]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe20]
set_property port_width 1 [get_debug_ports u_ila_0/probe20]
connect_debug_port u_ila_0/probe20 [get_nets [list system_i/ps7_0_axi_periph_n_42]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe21]
set_property port_width 1 [get_debug_ports u_ila_0/probe21]
connect_debug_port u_ila_0/probe21 [get_nets [list system_i/ps7_0_axi_periph_n_43]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe22]
set_property port_width 1 [get_debug_ports u_ila_0/probe22]
connect_debug_port u_ila_0/probe22 [get_nets [list system_i/ps7_0_axi_periph_n_44]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe23]
set_property port_width 1 [get_debug_ports u_ila_0/probe23]
connect_debug_port u_ila_0/probe23 [get_nets [list system_i/ps7_0_axi_periph_n_45]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe24]
set_property port_width 1 [get_debug_ports u_ila_0/probe24]
connect_debug_port u_ila_0/probe24 [get_nets [list system_i/ps7_0_axi_periph_n_46]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe25]
set_property port_width 1 [get_debug_ports u_ila_0/probe25]
connect_debug_port u_ila_0/probe25 [get_nets [list system_i/ps7_0_axi_periph_n_47]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe26]
set_property port_width 1 [get_debug_ports u_ila_0/probe26]
connect_debug_port u_ila_0/probe26 [get_nets [list system_i/ps7_0_axi_periph_n_48]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe27]
set_property port_width 1 [get_debug_ports u_ila_0/probe27]
connect_debug_port u_ila_0/probe27 [get_nets [list system_i/ps7_0_axi_periph_n_49]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe28]
set_property port_width 1 [get_debug_ports u_ila_0/probe28]
connect_debug_port u_ila_0/probe28 [get_nets [list system_i/ps7_0_axi_periph_n_50]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe29]
set_property port_width 1 [get_debug_ports u_ila_0/probe29]
connect_debug_port u_ila_0/probe29 [get_nets [list system_i/ps7_0_axi_periph_n_51]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe30]
set_property port_width 1 [get_debug_ports u_ila_0/probe30]
connect_debug_port u_ila_0/probe30 [get_nets [list system_i/ps7_0_axi_periph_n_52]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe31]
set_property port_width 1 [get_debug_ports u_ila_0/probe31]
connect_debug_port u_ila_0/probe31 [get_nets [list system_i/ps7_0_axi_periph_n_53]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe32]
set_property port_width 1 [get_debug_ports u_ila_0/probe32]
connect_debug_port u_ila_0/probe32 [get_nets [list system_i/ps7_0_axi_periph_n_54]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe33]
set_property port_width 1 [get_debug_ports u_ila_0/probe33]
connect_debug_port u_ila_0/probe33 [get_nets [list system_i/ps7_0_axi_periph_n_55]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe34]
set_property port_width 1 [get_debug_ports u_ila_0/probe34]
connect_debug_port u_ila_0/probe34 [get_nets [list system_i/ps7_0_axi_periph_n_56]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe35]
set_property port_width 1 [get_debug_ports u_ila_0/probe35]
connect_debug_port u_ila_0/probe35 [get_nets [list system_i/ps7_0_axi_periph_n_57]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe36]
set_property port_width 1 [get_debug_ports u_ila_0/probe36]
connect_debug_port u_ila_0/probe36 [get_nets [list system_i/ps7_0_axi_periph_n_58]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe37]
set_property port_width 1 [get_debug_ports u_ila_0/probe37]
connect_debug_port u_ila_0/probe37 [get_nets [list system_i/ps7_0_axi_periph_n_59]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe38]
set_property port_width 1 [get_debug_ports u_ila_0/probe38]
connect_debug_port u_ila_0/probe38 [get_nets [list system_i/ps7_0_axi_periph_n_60]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe39]
set_property port_width 1 [get_debug_ports u_ila_0/probe39]
connect_debug_port u_ila_0/probe39 [get_nets [list system_i/ps7_0_axi_periph_n_61]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe40]
set_property port_width 1 [get_debug_ports u_ila_0/probe40]
connect_debug_port u_ila_0/probe40 [get_nets [list system_i/ps7_0_axi_periph_n_62]]
create_debug_port u_ila_0 probe
set_property PROBE_TYPE DATA_AND_TRIGGER [get_debug_ports u_ila_0/probe41]
set_property port_width 1 [get_debug_ports u_ila_0/probe41]
connect_debug_port u_ila_0/probe41 [get_nets [list system_i/ps7_0_axi_periph_n_63]]
set_property C_CLK_INPUT_FREQ_HZ 300000000 [get_debug_cores dbg_hub]
set_property C_ENABLE_CLK_DIVIDER false [get_debug_cores dbg_hub]
set_property C_USER_SCAN_CHAIN 1 [get_debug_cores dbg_hub]
connect_debug_port dbg_hub/clk [get_nets u_ila_0_FCLK_CLK0]
