# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/systemv1/systemv1.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==systemv1 || ORIG_REF_NAME==systemv1}]

# IP: bd/systemv1/ip/systemv1_processing_system7_0_0/systemv1_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==systemv1_processing_system7_0_0 || ORIG_REF_NAME==systemv1_processing_system7_0_0}]

# IP: bd/systemv1/ip/systemv1_axi_gpio_0_0/systemv1_axi_gpio_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==systemv1_axi_gpio_0_0 || ORIG_REF_NAME==systemv1_axi_gpio_0_0}]

# IP: bd/systemv1/ip/systemv1_axi_gpio_1_0/systemv1_axi_gpio_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==systemv1_axi_gpio_1_0 || ORIG_REF_NAME==systemv1_axi_gpio_1_0}]

# IP: bd/systemv1/ip/systemv1_axi_gpio_0_1/systemv1_axi_gpio_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==systemv1_axi_gpio_0_1 || ORIG_REF_NAME==systemv1_axi_gpio_0_1}]

# IP: bd/systemv1/ip/systemv1_ps7_0_axi_periph_0/systemv1_ps7_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==systemv1_ps7_0_axi_periph_0 || ORIG_REF_NAME==systemv1_ps7_0_axi_periph_0}]

# IP: bd/systemv1/ip/systemv1_rst_ps7_0_100M_0/systemv1_rst_ps7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==systemv1_rst_ps7_0_100M_0 || ORIG_REF_NAME==systemv1_rst_ps7_0_100M_0}]

# IP: bd/systemv1/ip/systemv1_xbar_0/systemv1_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==systemv1_xbar_0 || ORIG_REF_NAME==systemv1_xbar_0}]

# IP: bd/systemv1/ip/systemv1_auto_pc_0/systemv1_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==systemv1_auto_pc_0 || ORIG_REF_NAME==systemv1_auto_pc_0}]

# XDC: bd/systemv1/systemv1_ooc.xdc
