# 
# Synthesis run script generated by Vivado
# 

create_project -in_memory -part xc7z010clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.cache/wt [current_project]
set_property parent.project_path C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib {
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/clk_div.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/clk_gen.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/clkx_bus.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/cmd_parse.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/dac_spi.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/debouncer.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/lb_ctl.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/meta_harden.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/out_ddr_flop.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/reset_bridge.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/resp_gen.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/rst_gen.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/samp_gen.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/samp_ram.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/system_wrapper.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/to_bcd.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/uart_baud_gen.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/uart_rx.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/uart_rx_ctl.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/uart_tx.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/uart_tx_ctl.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/wave_gen.v
  C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/imports/lab4/wave_gen_top.v
}
add_files C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/bd/system/system.bd
set_property used_in_implementation false [get_files -all c:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/bd/system/ip/system_processing_system7_0_0/system_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/bd/system/system_ooc.xdc]
set_property is_locked true [get_files C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/bd/system/system.bd]

read_ip -quiet C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/clk_core/ip/clk_core/clk_core.xci
set_property used_in_implementation false [get_files -all c:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/clk_core/ip/clk_core/clk_core_board.xdc]
set_property used_in_implementation false [get_files -all c:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/clk_core/ip/clk_core/clk_core.xdc]
set_property used_in_implementation false [get_files -all c:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/clk_core/ip/clk_core/clk_core_ooc.xdc]
set_property is_locked true [get_files C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/clk_core/ip/clk_core/clk_core.xci]

read_ip -quiet C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/ip/char_fifo/char_fifo.xci
set_property used_in_implementation false [get_files -all c:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/ip/char_fifo/char_fifo.xdc]
set_property used_in_implementation false [get_files -all c:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/ip/char_fifo/char_fifo_clocks.xdc]
set_property used_in_implementation false [get_files -all c:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/ip/char_fifo/char_fifo_ooc.xdc]
set_property is_locked true [get_files C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/sources_1/ip/char_fifo/char_fifo.xci]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/constrs_1/imports/lab4/wave_gen_pins_Zybo.xdc
set_property used_in_implementation false [get_files C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/constrs_1/imports/lab4/wave_gen_pins_Zybo.xdc]

read_xdc C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/constrs_1/imports/lab4/wave_gen_timing_Zybo.xdc
set_property used_in_implementation false [get_files C:/xup/fpga_flow/2016_2_zynq_labs/lab4/lab4.srcs/constrs_1/imports/lab4/wave_gen_timing_Zybo.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]

synth_design -top wave_gen_top -part xc7z010clg400-1


write_checkpoint -force -noxdef wave_gen_top.dcp

catch { report_utilization -file wave_gen_top_utilization_synth.rpt -pb wave_gen_top_utilization_synth.pb }
